### ISSUE TITLE
Why is Travis CI configured to check against so many versions of Cabal and GHC?

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/inflections-hs#12]
Right now, the Travis CI build is configured to check this package against 17 version combinations of Cabal and GHC.

Can we remove some of them?

We need to check against 7.8.4 (LTS Haskell) and up, but I think we can remove some of the remaining ones (7.0.*, 7.2.*, 7.4.*, 7.6.*).

**Comment by jsl** [comment]
I think the current travis file was contributed by an outside user, but I'm not sure if they were using an old GHC that didn't work with inflections, or if something else motivated the change. I'd be ok with making the file more standard, and getting rid of some really old GHC versions that it doesn't seem likely anyone is using anymore. If we're changing this, we may want to follow [the PR](https://github.com/stackbuilders/twitter-feed/commit/e15c2f5ce870e86cedda3d6219bf3eac4c6ac100) made by @juanpaucar on twitter-feed, since that seems to be the way that Travis wants to be configured now.

**Comment by jpvillaisaza** [comment]
@jsl Sounds good.

**Comment by juanpaucar** [comment]
So i'm going to move this to the containers in travis... but since we usually use ghc 7.6, 7.8 and 7.10; i'd remove the other ghc versions. Is this ok @jsl @jpvillaisaza ?

**Comment by jsl** [comment]
Sure! If this Travis recipe is working well, I think we have about 10 other
projects that could use it too! Maybe even a short blog post with our
Travis config so that it's easy to find for other haskellers looking for
idiomatic, simple Travis confogs?

On Friday, July 24, 2015, Juan Paucar <notifications@github.com> wrote:

> So i'm going to move this to the containers in travis... but since we
> usually use ghc 7.6, 7.8 and 7.10; i'd remove the other ghc versions. Is
> this ok @jsl <https://github.com/jsl> @jpvillaisaza
> <https://github.com/jpvillaisaza> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stackbuilders/inflections-hs/issues/12#issuecomment-124551384>
> .
>


-- 
Justin Leitgeb <http://justinleitgeb.com>
Twitter: @justinleitgeb <http://twitter.com/justinleitgeb>
Github: @jsl <https://github.com/jsl>

Co-Founder and CTO, Stack Builders Inc. <http://www.stackbuilders.com>

**Comment by jpvillaisaza** [comment]
@juanpaucar @jsl Sounds good to me (updating the Travis configuration and the blog post).

**Comment by juanpaucar** [comment]
So we have this repo https://github.com/hvr/multi-ghc-travis .
It hasn't been updated yet, although there's an issue from April https://github.com/hvr/multi-ghc-travis/issues/17 .

I could write something short if you want it that post

**Comment by jpvillaisaza** [comment]
Done. See https://github.com/stackbuilders/inflections-hs/commit/4813adec73a03063f71e58bd337e3cc45f1b7470.
